# Stop callmedia console Service
- hosts: all
  tasks:
  - name: check "callmedia console" service exists
    win_shell: Get-Service -name "callmedia console" -ea SilentlyContinue | Select-Object -Property status | Format-List
    register: callmedia console_status

#  - name: debug
#    debug:
#       var: "callmedia enterprise_status"

  - name: Stop and disable console service
#    debug:
#       msg: "status in w32time_status"
    win_service:
      name: "callmedia console"
      state: stopped
      start_mode: auto
#   when: callmedia enterprise_status.stdout | search("Status")

# Taking Backup of exiting callmedia console folder
- hosts: all
  tasks:
  - name: Copy a single file
    win_shell: echo %HOMEDIR%
    args:
      executable: cmd
    register: homedir_out

  - name: Backup of exiting callmedia console folder
    win_copy:
      src: C:\Program Files (x86)\Callmedia\CMConsole
      dest: C:\CM-console-bck
      remote_src: yes

# copy code zip on local
#---
- hosts: localhost
  tasks:
  - name: Ansible zip file with path example
    archive:
      path: "/root/myagent/vsts-build/r1/a/_DevOPs\ Experiment\ -Ansible-deployment/CMConsole"
      dest: /tmp/ansible-demo/CMConsole.zip
      format: zip

# copy code zip to remote machine
- hosts: all
  gather_facts: no
  tasks:
  - name: Copy the code
    win_copy:
      src: "/tmp/ansible-demo/CMConsole.zip"
      dest: C:\\CM-console-bck\\

  - name: Extract code
    win_unzip:
      src: C:\\CM-console-bck\\CMConsole.zip
      dest: C:\\Program Files (x86)\\Callmedia\\CMConsole\\

# Start callmedia console Service
- hosts: all
  tasks:
  - name: check "callmedia console" service exists
    win_shell: Get-Service -name "callmedia console" -ea SilentlyContinue | Select-Object -Property status | Format-List
    register: callmedia console_status

#  - name: debug
#    debug:
#       var: "callmedia enterprise_status"

  - name: Stop and disable console service
#    debug:
#       msg: "status in w32time_status"
    win_service:
      name: "callmedia console"
      state: started
      start_mode: auto
#   when: callmedia enterprise_status.stdout | search("Status")
