# Stop callmedia desktop Service
- hosts: all
  tasks:
  - name: check "callmedia desktop" service exists
    win_shell: Get-Service -name "callmedia desktop" -ea SilentlyContinue | Select-Object -Property status | Format-List
    register: callmedia desktop_status

#  - name: debug
#    debug:
#       var: "callmedia desktop_status"

  - name: Stop and disable desktop service
#    debug:
#       msg: "status in w32time_status"
    win_service:
      name: "callmedia desktop"
      state: stopped
      start_mode: auto
#   when: callmedia desktop_status.stdout | search("Status")

# Taking Backup of exiting callmedia desktop folder
- hosts: all
  tasks:
  - name: Copy a single file
    win_shell: echo %HOMEDIR%
    args:
      executable: cmd
    register: homedir_out

  - name: Backup of exiting callmedia enterprise folder
    win_copy:
      src: C:\Program Files (x86)\Callmedia\CMEnterprise\Callmedia Desktop
      dest: C:\CM-desktop-bck
      remote_src: yes

# copy code zip on local
#---
- hosts: localhost
  tasks:
  - name: Ansible zip file with path example
    archive:
      path: "/root/myagent/vsts-build/r1/a/_DevOPs\ Experiment\ -Ansible-deployment/CMDesktop"
      dest: /tmp/ansible-demo/CMDesktop.zip
      format: zip

# copy code zip to remote machine
- hosts: all
  gather_facts: no
  tasks:
  - name: Copy the code
    win_copy:
      src: "/tmp/ansible-demo/CMDesktop.zip"
      dest: C:\\CM-enterprise-bck\\

  - name: Extract code
    win_unzip:
      src: C:\\CM-enterprise-bck\\CMEnterprise.zip
      dest: C:\\Program Files (x86)\\Callmedia\\Callmedia Desktop\\

# Start callmedia enterprise Service
- hosts: all
  tasks:
  - name: check "Callmedia Desktop" service exists
    win_shell: Get-Service -name "Callmedia Desktop" -ea SilentlyContinue | Select-Object -Property status | Format-List
    register: callmedia enterprise_status

#  - name: debug
#    debug:
#       var: "callmedia desktop_status"

  - name: Stop and disable enterprise service
#    debug:
#       msg: "status in w32time_status"
    win_service:
      name: "Callmedia Desktop"
      state: started
      start_mode: auto
#   when: Callmedia Desktop_status.stdout | search("Status")
